# Nixpacks configuration for Node.js app
[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
PORT = "3000"
